---
#K8s YAML Spec file for a PostgreSQL deployment
#Author: PNT@09Mar2022
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: demo-voting-app
    createdby: PNT

spec:
  replicas: 1

  selector:
    matchLabels:
      name: postgres-pod
    
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app
    
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRE_USER
              value: 'postgres'
            - name: POSTGRES_PASSWORD
              value: 'postgres'
...