---
#K8s YAML Spec file for a simple worker app (part of a Microservices stack) deployment
#Author: PNT@09Mar2022
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    createdby: PNT

spec:
  replicas: 1

  selector:
    matchLabels:
      name: worker-app-pod
  
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
...