---
#K8s YAML Spec file for a Redis Service
#ClusterIP Service
#Author: PNT@09Mar2022
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    createdby: PNT
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  
  selector:
    name: redis-pod
    app: demo-voting-app
...