---
#K8s YAML Spec file for a simple voting result app (part of a Microservices stack)
#NodePort Service
#Author: PNT@09Mar2022
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    createdby: PNT
spec:
  type: NodePort
  
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30302
  
  selector:
    name: result-app-pod
    app: demo-voting-app
...