---
#K8s YAML Spec file for a PostgreSQL PG Admin Service
#NodePort Service
#Author: PNT@10Mar2022
apiVersion: v1
kind: Service
metadata:
  name: bu-pgadmin-service
  labels:
    name: bu-pgadmin-service
    createdby: PNT

spec:
  type: NodePort

  ports:
    - port: 80
      targetPort: 80
      nodePort: 31113
  
  selector:
    name: bu-pgadmin-pod
    tier: database
    group: mgmt-tools
...